# Generated by Django 5.0.7 on 2024-07-18 22:44

from django.db import migrations

def create_initial_blog_posts(apps, schema_editor):
    BlogPost = apps.get_model('react_project_api', 'BlogPost')
    BlogPost.objects.create(title='First Post', content='This is the content of the first post.')
    BlogPost.objects.create(title='Second Post', content='This is the content of the second post.')

class Migration(migrations.Migration):

    dependencies = [
        ('react_project_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_blog_posts),
    ]
